FoodSelling/ViewModels/CartViewModel.cs
namespace FoodSelling.ViewModels
{
    public class CartViewModel
    {
        public int CartCount { get; set; }
    }
}

FoodSelling/Controllers/CartController.cs
using FoodSelling.Models;
using FoodSelling.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cors.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FoodSelling.Controllers
{
    [Authorize]
    public class CartController : BaseController
    {       

        public CartController(CartService cartService) : base(cartService: cartService) 
        {            
        }
        public async Task<IActionResult> Index()
        {
            var cart = await _cartService.GetCartItems();
            return View(cart);
        }
       
        public async Task<IActionResult> RemoveFromCart(int foodId)
        {
            await _cartService.RemoveFromCart(User.Identity.Name,foodId);
            return RedirectToAction("Index");
        }

       
        public async Task<IActionResult> UpdateCart(int foodId,int qty)
        {
            if (qty < 0)
            {
                qty = -1 * (qty + 1);
            }
            else
            {
                qty = qty + 1;
            }            
            await _cartService.UpdateCart(User.Identity.Name, foodId,qty);
            return RedirectToAction("Index");
        }

       
        public async Task<IActionResult> ClearCart()
        {
            await _cartService.ClearCart(User.Identity.Name);
            return RedirectToAction("Index");
        }       
    }
}

FoodSelling/Controllers/CheckoutController.cs
using FoodSelling.Models;
using FoodSelling.Service;
using FoodSelling.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FoodSelling.Controllers
{
    [Authorize]
    public class CheckoutController : BaseController
    {
        public CheckoutController(AppDbContext appDbContext,CartService cartService):base(appDbContext:appDbContext,cartService:cartService)
        {
            
        }
        public async Task<IActionResult> Index()
        {
            var cartItem = await _cartService.GetCartItems();
            var totalAmount = cartItem.Sum(c => c.Price * c.Quantity);
            var checkoutViewModel = new CheckoutViewModel
            {
                CartItems = cartItem.ToList(),
                TotalAmount = totalAmount,
            };
            return View(checkoutViewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> PlaceOrder(CheckoutViewModel checkoutViewModel)
        {
            var cartItem = await _cartService.GetCartItems();
            var totalAmount = cartItem.Sum(c => c.Price * c.Quantity);
            checkoutViewModel.CartItems = cartItem.ToList();
            checkoutViewModel.TotalAmount = totalAmount;
            if (!ModelState.IsValid)
            {
                return View("Index", checkoutViewModel);
            }
           
            var order = new Order
            {
                CustomerEmail = User.Identity.Name,
                CustomerName = User.Identity.Name,
                Quantity = cartItem.Sum(c=>c.Quantity),
                Status = "Order Confirmed",
                OrderDate = DateTime.Now,
                Address = checkoutViewModel.ShippingAddress,
                TotalAmount = totalAmount,
                OrderItems = cartItem.Select(item => new OrderItem
                {
                    FoodItemId = item.ProductId,
                    Quantity = item.Quantity
                }).ToList()
            };
           
            using (var transaction = await _appDbContext.Database.BeginTransactionAsync())
            {
                try {
                    await _appDbContext.Orders.AddAsync(order);
                    await _appDbContext.SaveChangesAsync();                  
                    await transaction.CommitAsync();
                    await _cartService.ClearCart(User.Identity.Name);
                    return RedirectToAction("Index","Order");
                    //return RedirectToAction("Confirmation", new { orderId = order.OrderId });
                }
                catch
                {
                    transaction.Rollback();
                    // Log the exception for debugging
                    // For example, you can use a logging framework like NLog, Serilog, or log to a file.
                    //throw new Exception("An error occurred while processing the order. The transaction has been rolled back.", ex);
                    ModelState.AddModelError("", "An error occurred while placing the order. Please try again later.");
                    return View("Index", checkoutViewModel);
                }
            }                                                         
        }

        public ActionResult Confirmation(int orderId)
        {
            var order = _appDbContext.Orders.Find(orderId);
            if (order == null)
            {
                return View(order);
            }

            return View(order);
        }
    }
}

FoodSelling/Views/Cart/Index.cshtml
@model IEnumerable<CartItem>


<div>
    @if (Model.Count() > 0)
    {
        <a class="m-2" href="@Url.Action("ClearCart", "Cart")">Clear All</a>
    }
    else
    {
        <a class="m-2" href="@Url.Action("Index", "Home")">Add</a>
    }
    
</div>
<table>
    <thead>
        <tr>
            <th>Product Name</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.ProductName</td>
                <td>@item.Price</td>
                <td>@item.Quantity</td>
                <td>
                    <div class="p-2">
                        <a class="m-2" href="@Url.Action("RemoveFromCart", "Cart", new { foodId = item.ProductId })">Remove</a>
                        <a class="m-2" href="@Url.Action("UpdateCart", "Cart", new { foodId = item.ProductId, qty = item.Quantity })">Qty(+)</a>
                        @if (item.Quantity > 1)
                        {
                            <a class="m-2" href="@Url.Action("UpdateCart", "Cart", new { foodId = item.ProductId, qty = (-1 * item.Quantity)})">Qty(-)</a>
                        }                       
                       
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
<div>
    @if (Model.Count() > 0)
    {
        <a class="m-2" href="@Url.Action("Index", "Checkout")">Order Now</a>
    }
</div>